//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGlobalizationApp.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectGlobalizationApp.App_GlobalResources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol - Espanha.
        /// </summary>
        public static string EspanholEspanha {
            get {
                return ResourceManager.GetString("EspanholEspanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês - Estados Unidos.
        /// </summary>
        public static string InglesAmericano {
            get {
                return ResourceManager.GetString("InglesAmericano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicação de Globalização.
        /// </summary>
        public static string NomeAplicacao {
            get {
                return ResourceManager.GetString("NomeAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português - Brasil.
        /// </summary>
        public static string PortuguesBrasil {
            get {
                return ResourceManager.GetString("PortuguesBrasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu aplicativo ASP.NET.
        /// </summary>
        public static string Rodape {
            get {
                return ResourceManager.GetString("Rodape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá!.
        /// </summary>
        public static string Saudacao {
            get {
                return ResourceManager.GetString("Saudacao", resourceCulture);
            }
        }
    }
}
